### PR TITLE
add arm target for compilation

### PR DESCRIPTION
**Pull request by pabloaledo**
Hey, first time doing PR here (have done some on bioconda before). Is everyting ok?. This is related to https://github.com/bioconda/bioconda-recipes/pull/47056#issuecomment-2095692129

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pabloaledo** [comment]
@conda-forge-admin, please rerender

**Comment by druvus** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
I do not see any aarch64 related changes in this PR!
I'd expect to see something like https://github.com/conda-forge/perl-encode-feedstock/pull/4/files#diff-478786365dd93f740eb520c2faa03d7a0623273663b75472272c8ef94297bbe2R7-R8 to actually add aarch64 build

**Comment by martin-g** [comment]
I've opened https://github.com/conda-forge/perl-encode-feedstock/pull/5

**Comment by martin-g** [comment]
#5 has been merged!

**Review by xileF1337 — APPROVED** [review]

**Pull request closed without merging**
